apiVersion: v1
kind: Pod
metadata: 
  name: pod-4
spec:
    containers: 
    - name: nginx-container
      image: nginx:latest
      env:
      - name: batch
        value: "55"
      - name: Environment
        value: dev
      - name: MONGO_URL
        value: mongo.corp.cc
      - name: BU      
        value: ECOM