apiVersion: v1
kind: Pod
metadata:
  name: multi-container-po
  annotations:
    kubernetes.io/config.mirror: "df7cc47f8477b6b1226d7d23a904867b"  # Add this annotation
spec:
  containers:
  - name: container1
    image: nginx
    ports:
    - containerPort: 80
  - name: container2
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo Hello from container2; sleep 10; done"]
