apiVersion: v1
kind: Pod
metadata:
  name: nginx-mirror-pod
  annotations:
    kubernetes.io/config.mirror: "mirror-pod-nginx"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
