# apiVersion:
# kind: 
# metadata:
# spec:

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    kubernetes.io/config.mirror: "true"
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
