apiVersion: v1
kind: Pod
metadata:
  name: my-static-pod
  annotations:
    kubernetes.io/config.hash: "df7cc47f8477b6b1226d7d23a904867b"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
