# apiVersion:
# kind: 
# metadata:
# spec:

apiVersion: v1
kind: Pod
metadata:
  name: nginx-mirror
spec:
  nodeName: ip-172-31-74-253.ec2.internal
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
