# apiVersion:
# kind: 
# metadata:
# spec:

apiVersion: v1
kind: Pod
metadata:
  name: nginx-mirror
spec:
  nodeName: prem-node-group  # Replace <node_name> with the actual node name
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
