# apiVersion: v1
# kind: Pod
# metadata:
#   name: my-static-pod
#   annotations:
#     kubernetes.io/config.hash: "df7cc47f8477b6b1226d7d23a904867b"
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     ports:
#     - containerPort: 80


apiVersion: v1
kind: Pod
metadata:
  name: nginx:latest
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - ip-172-31-3-104.ec2.internal
            - ip-172-31-74-253.ec2.internal
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
