apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  nodeName: ip-172-31-24-198.ec2.internal  # Specify the name of the node where you want the pod to run
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
