# apiVersion:
# kind: 
# metadata:
# spec:

apiVersion: v1
kind: Pod
metadata:
  name: nginx-mirror
  annotations:
    kubernetes.io/config.mirror: ip-172-31-3-104.ec2.internal
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
