# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
# spec:
#   containers:
#   - name: nginx
#     image: nginx:latest
#     ports:
#     - containerPort: 80

apiVersion: v1
kind: Pod
metadata:
  name: nginx-mirror
  annotations:
    kubernetes.io/config.mirror: "df7cc47f8477b6b1226d7d23a904867b"
spec:
  containers:
  - name: nginx
    image: nginx
